os: linux
language: node_js
node_js:
- node
- 12
- 10
script:
- npm run lint
- npm test
- npm run docs
- npm run build
deploy:
- provider: npm
  email: stefandesu@exo.pm
  api_token:
    secure: Foh3uMwotb5EVEDJs5V9RP7uqOhDVDXkFTZBqKQIDx5Ub99XrGbEBZF92J5b/yx2xsliCJkp4drs+0iHn8VHjxBMChUCBJI3hVp+ZWsqgo/W1ZL/akL754xSv6LbUzOAqau8a6i29/+h4NndtCXaQmM+jyZ73GX7woEi09ECoErpU0cd7q+H3ua5J0BOr6RO8XhuW7zcAkZYGCyDrqk6Vve5pE8/szctJrPYnQ0OndKNKWluyGTor5M+HPE2L0eWwXKDVEMKAdMekBvYqOFEthoYV0aVaXu4cxKcSdDlijkmoc4bnIElDatKbeNaSnC5V1DZaKfG/FZ4BEA4P/NULfmEu5QG+KnjsL95mDOMOOYfs1+qmmeieSseah9okyYOv01OlNgaqfXwMCR0ztCf/MF+0w/QPKoVsvR3j5IJYGsObhCXgzuXwRXtAli1LqjthbE4sgXj6rd2aErbAOBhGd+LoXRC6hlP8EW8SA+rriEYAfI4amXZBXgrzAHtTkJeUXPIBWpTZcYj9TwU/rTB+vvmJ3lKVzIZo0zbDe1NPKsSXGDmqwv/m8fLONbEQIw+H6n70o/uhJJkCiWZUdEnYkUWiHBXNjqH6675a4vHxvjL0uaQzfw4xPqnW0SDcTZ+Q0bUyU7mEtC4d83XZm1GvoLage2sSvFEMD621aByEG8=
  on:
    node_js: node
    tags: true
    branch: master
  edge: true
- provider: pages
  local_dir: jsdoc/build
  token: "$GITHUB_TOKEN"
  on:
    node_js: node
    tags: false
    branch: master
  edge: true
